@subDomain = [Your Logic app subdomain here]
@sig = [Your Logic app signature here]


@hostname = {{subDomain}}.azurewebsites.net
@protocol = https
@port = 443
@host = {{hostname}}:{{port}}
@content-type = application/json

@checkInAPI = Check-In/triggers/When_a_HTTP_request_is_received/invoke?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig={{sig}}

POST {{protocol}}://{{host}}/api/{{checkInAPI}} HTTP/1.1
Content-Type: {{content-type}}

{
    "appointment_id": "123",
    "patient_name": "John Smith"
}